- set_fact:
  tags: linux

- set_fact:
  tags: windows

#change httpd.conf to listen only on port 8080
- name: install apache on linux
  import_role:
    name: functions
    tasks_from: httpd
  tags: 
    - apache
    - all
  when: ansible_os_family == "RedHat"

- import_tasks: Windows.yml
  when: ansible_os_family == "Windows"

# install iis and Create a test website on the IIS on port 80
- name: install iis on windows and create site
  import_role:
    name: functions
    tasks_from: enable_iis
  tags: 
    - enable_iis
    - all

