
# remark - had troubles to create Centos - 
# in case that i had one, i would use jinja to change listen section in conf file of httpd.
# ANSIBLE: 
## - replace:
##  # path: /path/to/file
##  # regexp: 'string or regular expression for search'
##  # replace: 'word to replace the search string'
##  # backup: yes
##  
## EXAMPLE: 
##
## Apache HTTP server - main configuration
##
##
## General configuration
## ServerRoot {{ httpd_server_root }}
## Listen {{ httpd_listen }} - by replace in ansible i would put a regexp change pattern to change the port and hosrt the web server page
## ...
## ...
## 

- name: httpd installed
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: custom index.html
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: |
              Custom Web Page

- name: httpd service enabled
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started

- name: open firewall
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true